### ISSUE TITLE
Add support for Mac OS X

### ISSUE THREAD

**Issue by daknob** [DaKnOb/Zipper#1]
Add support for Mac OS X by fixing the `head(1)` issue:

In Linux, `head(1)` supports arguments in the form of `-c 100K`.
In Mac OS X, `head(1)` only supports arguments in the form of `-c 102400`.

**Comment by ru108** [comment]
https://github.com/DaKnOb/Zipper/blob/master/zipper.py#L32

```
        command = "head -c " + str(size * 1024 * 1024) + " " + SourceFile
```

**Comment by daknob** [comment]
It is not that simple. You need to convert the "1k", "1M", "1G" from `size` to the appropriate amount of `1024`'s. It will take 2 minutes of work.. :-)

**Comment by ru108** [comment]
Ok )

```
size_n = {'k': 1024, 'm': 1024*1024, 'g': 1024*1024*124}
...
        size_in_bytes *= size_n[UnitSize.lower()] if UnitSize.lower() in size_n.keys() else 1
        command = "head -c " + str(size_in_bytes) + " " + SourceFile
```

**Comment by ru108** [comment]
Sorry, mistake

that

```
size_n = {'k': 1024, 'm': 1024*1024, 'g': 1024*1024*124}
...
size_in_bytes = size

if UnitSize.lower() in size_n.keys():
    size_in_bytes *= size_n[UnitSize.lower()]
command = "head -c " + str(size_in_bytes) + " " + SourceFile
```
